default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: banksy_dev

test:
  <<: *default
  database: banksy_test
production:
  <<: *default
  database: banksy_prod
  username: banksy
  password: <%= ENV['DATABASE_PASSWORD'] %>
